// The formatter that makes the bot's commits readable.
//
// Four files in this repository are regenerated by a scheduled workflow and pushed to main:
// fingerprints.json, hero-index.json and the site's heroes and categories tables. They were
// written on a single line each, so every one of those commits showed as one changed line and
// said nothing about what changed. tools/json-lines.js breaks a record onto its own line.
//
// One property matters above the shape of the output: this is a formatter. Whatever comes out
// has to parse back to what went in, because the app downloads one of these files and the
// site builds its pages from the other three. The tests here are mostly that property, plus
// the corners where JSON itself is lossy (undefined, holes in an array) and a formatter can
// quietly disagree with JSON.stringify about them.
const test = require('node:test');
const assert = require('node:assert/strict');

const { jsonLines, jsonLinesFile } = require('../tools/json-lines.js');

/** What the file is for: parse it back and you have the value you started with. */
const roundTrips = (value) => assert.deepEqual(JSON.parse(jsonLines(value)), JSON.parse(JSON.stringify(value)));

test('a value survives the round trip whatever shape it is', () => {
  for (const value of [
    { count: 2, mods: { aa: [{ name: 'A', categoryId: 'heroes' }], bb: [{ name: 'B', categoryId: 'wards' }] } },
    [1, 'two', null, true, { four: [5] }],
    { nested: { deep: { deeper: { deepest: Array.from({ length: 40 }, (_, i) => ({ i, pad: 'x'.repeat(20) })) } } } },
    'a bare string',
    42,
    null,
    {},
    [],
  ]) roundTrips(value);
});

test('a record that fits on a line keeps it, and the container holding many of them opens up', () => {
  const value = { mods: { a: [{ name: 'A' }], b: [{ name: 'B' }], c: [{ name: 'C' }] } };
  const out = jsonLines(value, { inlineAt: 40 });
  const lines = out.split('\n');

  // one line per record is the whole point: three mods, three lines carrying a name
  assert.equal(lines.filter((l) => l.includes('"name"')).length, 3);
  // and each of those lines carries its record whole, rather than a brace on its own
  assert.ok(lines.some((l) => l.trim().startsWith('"a": [{"name":"A"}]')), out);
});

test('a record longer than the limit is broken up rather than left to run off the screen', () => {
  const wide = { mods: Array.from({ length: 30 }, (_, i) => ({ name: `mod ${i}`, categoryId: 'heroes' })) };
  const out = jsonLines(wide, { inlineAt: 60 });

  assert.ok(out.split('\n').length > 30, 'thirty mods should not share a line');
  assert.ok(out.split('\n').every((l) => l.length < 200), 'no line should be a wall');
  roundTrips(wide);
});

test('the whole value stays on one line when it is small enough to read at a glance', () => {
  assert.equal(jsonLines({ heroes: 2, mods: 5 }), '{"heroes":2,"mods":5}');
});

test('keys JSON drops are dropped here too, rather than becoming null in an object', () => {
  const value = { kept: 'yes', gone: undefined, fn: () => {}, long: 'x'.repeat(300) };
  assert.deepEqual(JSON.parse(jsonLines(value)), { kept: 'yes', long: 'x'.repeat(300) });
});

test('a hole in an array is null, the way JSON.stringify writes it', () => {
  const value = { list: [1, undefined, 3, 'x'.repeat(300)] };
  assert.deepEqual(JSON.parse(jsonLines(value)).list, [1, null, 3, 'x'.repeat(300)]);
});

test('the file form ends on a newline, and only one', () => {
  const out = jsonLinesFile({ a: 1 });
  assert.ok(out.endsWith('}\n'));
  assert.equal(out.split('\n').length, 2);
});

test('indentation nests, so a diff shows where in the file it happened', () => {
  const out = jsonLines({ outer: { inner: { name: 'x'.repeat(300) } } }, { inlineAt: 20 });
  assert.match(out, /^\{\n {2}"outer": \{\n {4}"inner": \{\n {6}"name":/);
});

test('a real fingerprint map comes out one fingerprint per line', () => {
  // the shape tools/gen-fingerprints.js writes: fp -> the catalog entries that share the file
  const map = {
    count: 3,
    mods: Object.fromEntries(
      ['a1', 'b2', 'c3'].map((fp) => [fp, [{ name: `Mod ${fp}`, categoryId: 'heroes', styleLabel: null, type: 'vpk' }]]),
    ),
    fonts: [{ name: 'Monocraft', categoryId: 'fonts', styleLabel: null, files: { 'a.ttf': 'deadbeef' } }],
  };
  const lines = jsonLines(map).split('\n');

  assert.equal(lines.filter((l) => l.trim().startsWith('"a1"') || l.trim().startsWith('"b2"') || l.trim().startsWith('"c3"')).length, 3);
  roundTrips(map);
});
