name: Discord Release Webhook

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send discord notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
        run: |
          PAYLOAD=$(jq -n \
            --arg name "$RELEASE_NAME" \
            --arg url "$RELEASE_URL" \
            '{
              "content": "**Mod Manager Updated!**",
              "embeds": [
                {
                  "title": $name,
                  "url": $url,
                  "description": "A new release has been published!\n\n[**Open Release Page**](\($url))",
                  "color": 8585067
                }
              ],
              "username": "GitHub",
              "avatar_url": "https://i.postimg.cc/zGJTFHyj/github.webp"
            }')

          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
